services:
  blogapi:
    image: blogapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: blogapi-db
      DB_PORT: 5432
      SERVER_PORT: 3000
      SERVER_HOST: "0.0.0.0"
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "dist/server.js"]
